name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: alonso-github.action
          cx_tenant: cx_seg
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --threshold "sast-low=14" --filter "state=TO_VERIFY" --debug --scan-types sast,iac-security,sca,container-security
